### ISSUE TITLE
Review and revise ontology and vocabulary titles with a view to uniformity

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#118]
See https://github.com/LD4P/arm/issues/80#issuecomment-398461321

**Comment by zimeon** [comment]
BTW, the documentation generator is taking the page title for the vocabularies from the `rdfs.label` of the `void:Dataset` resource (see https://github.com/LD4P/arm/blob/master/tools/build-lode-docs.py#L48). It seems that the LODE service doesn't generate a title, perhaps because the vocabularies don't use the OWL description. I could change to get the title from somewhere else if needed

**Comment by rjyounes** [comment]
@zimeon I think I caught the inconsistencies you noted in https://github.com/LD4P/arm/issues/80#issuecomment-398461321; if you have time, would you mind reviewing the changes in https://github.com/LD4P/arm/commit/34009a5c00d681567a676eea4fcb199ad2607b38 to see if this is what you referred to?

Along with these changes I've added some rdfs:comments to the owl:Ontology and void:Dataset definitions. This means that when generating the documentation and temporarily converting skos:definitions to rdfs:comments, there will be two rdfs:comments. I don't know whether LODE will display one or both, and in what order - the skos:definition should be displayed first. If this doesn't work I can change them to skos:editorialNotes.

**Comment by zimeon** [comment]
Looks like those changes will make titles look better. Let me know if you'd like me to update docs

**Comment by rjyounes** [comment]
If it's easy, please go ahead. Then we can also see what happens with the rdfs:comments.

rdfs:label is the right place to get the dataset titles.
